name: scp 文件

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: 构建
    runs-on: ubuntu-22.04
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 构建 Docker 镜像
      run: |
        docker build -t blog:latest .

    - name: 保存 Docker 镜像为 tar 文件
      run: |
        docker save blog:latest | gzip > blog.tar.gz
  
    - name: 使用 scp 进行 ssh 管道传输
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "开始服务器脚本"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        first_ssh: |
          cd /ixyz/blog
          docker compose down
          docker rmi blog:latest
        scp: |
          ./blog.tar.gz => /ixyz/blog
          ./docker-compose.yml => /ixyz/blog
        last_ssh: |
          echo $LASTSSH 
          cd /ixyz/blog
          docker load -i blog.tar.gz
          docker compose up -d